"""
Visualization utilities for ML model optimization results.

This module reads performance metrics generated during benchmarking
and creates comparison plots between original and optimized models.
"""

from pathlib import Path
import matplotlib.pyplot as plt
import json


def load_metrics(metrics_file: Path):
    """
    Load metrics from a JSON or text-based report.
    """
    with open(metrics_file, "r") as f:
        return f.read()


def plot_bar_comparison(
    labels,
    original_values,
    optimized_values,
    title,
    ylabel,
    output_path,
):
    """
    Create a side-by-side bar chart comparison.
    """
    x = range(len(labels))
    width = 0.35

    plt.figure(figsize=(8, 5))
    plt.bar(x, original_values, width, label="Original")
    plt.bar([i + width for i in x], optimized_values, width, label="Optimized")

    plt.xticks([i + width / 2 for i in x], labels)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.legend()
    plt.tight_layout()

    plt.savefig(output_path, dpi=300)
    plt.close()


def visualize_comparison(original_metrics: dict, optimized_metrics: dict, output_dir: Path):
    """
    Generate comparison plots between original and optimized models.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # Inference time comparison
    plot_bar_comparison(
        labels=["Mean"],
        original_values=[original_metrics["inference_time_ms"]["mean"]],
        optimized_values=[optimized_metrics["inference_time_ms"]["mean"]],
        title="Inference Time Comparison",
        ylabel="Time (ms)",
        output_path=output_dir / "inference_time_comparison.png",
    )

    # Model size comparison
    plot_bar_comparison(
        labels=["Model Size"],
        original_values=[original_metrics["model_size_mb"]],
        optimized_values=[optimized_metrics["model_size_mb"]],
        title="Model Size Comparison",
        ylabel="Size (MB)",
        output_path=output_dir / "model_size_comparison.png",
    )

    # Memory usage comparison
    plot_bar_comparison(
        labels=["Memory Usage"],
        original_values=[original_metrics["memory_usage_mb"]],
        optimized_values=[optimized_metrics["memory_usage_mb"]],
        title="Memory Usage Comparison",
        ylabel="Memory (MB)",
        output_path=output_dir / "memory_usage_comparison.png",
    )


def load_metrics_from_text(file_path: Path):
    """
    Parse metrics from text report into a dictionary.

    This function assumes the format generated by MetricsLogger.
    """
    metrics = {}
    with open(file_path, "r") as f:
        lines = f.readlines()

    for line in lines:
        if "Mean:" in line:
            metrics.setdefault("inference_time_ms", {})["mean"] = float(line.split(":")[1])
        elif "Model Size" in line:
            metrics["model_size_mb"] = float(line.split(":")[1])
        elif "Memory Usage" in line:
            metrics["memory_usage_mb"] = float(line.split(":")[1])
        elif "Top-1" in line:
            metrics.setdefault("accuracy", {})["top_1"] = float(line.split(":")[1].replace("%", ""))
        elif "Top-5" in line:
            metrics.setdefault("accuracy", {})["top_5"] = float(line.split(":")[1].replace("%", ""))

    return metrics


def main():
    """
    Entry point for visualization generation.
    """
    base_dir = Path(__file__).parent
    results_dir = base_dir / "results"
    plots_dir = results_dir / "plots"

    original_report = results_dir / "original_metrics.txt"
    optimized_report = results_dir / "optimized_metrics.txt"

    original_metrics = load_metrics_from_text(original_report)
    optimized_metrics = load_metrics_from_text(optimized_report)

    visualize_comparison(
        original_metrics,
        optimized_metrics,
        plots_dir,
    )

    print("Visualization completed. Plots saved to results/plots/")


if __name__ == "__main__":
    main()
